# Generated by Django 6.0.6 on 2026-06-20 15:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sorteo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_sorteo", models.CharField(db_index=True, max_length=20)),
                ("fecha", models.DateField(db_index=True)),
                (
                    "bolas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField()
                    ),
                ),
                (
                    "especiales",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField(), blank=True, null=True
                    ),
                ),
            ],
            options={
                "db_table": "sorteo",
                "ordering": ("tipo_sorteo", "fecha"),
                "managed": False,
            },
        ),
    ]
