# Generated by Django 6.0.6 on 2026-07-06 05:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrediccionSemanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_sorteo", models.CharField(db_index=True, max_length=20)),
                ("anio", models.IntegerField(db_index=True)),
                ("semana", models.IntegerField(db_index=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "prediccion_semanal",
                "ordering": ("-anio", "-semana", "tipo_sorteo"),
                "unique_together": {("tipo_sorteo", "anio", "semana")},
            },
        ),
        migrations.CreateModel(
            name="CombinacionPredicha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.IntegerField()),
                ("estrategia", models.CharField(max_length=50)),
                (
                    "bolas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField()
                    ),
                ),
                (
                    "especiales",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField(), blank=True, null=True
                    ),
                ),
                ("aciertos_por_sorteo", models.JSONField(blank=True, default=dict)),
                ("procesado", models.BooleanField(default=False)),
                (
                    "prediccion_semanal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combinaciones",
                        to="analytics.prediccionsemanal",
                    ),
                ),
            ],
            options={
                "db_table": "combinacion_predicha",
                "ordering": ("prediccion_semanal", "orden"),
            },
        ),
    ]
